export const ropeRoutes = [
  {
    name: "The Wurliest Burliest Man",
    grade: "5.10",
    color: "blue",
    type: "lead",
    id: "00001",
    image: "/img/rope1.jpg",
    description: "A super fun climb with a lot of exposure",
    date: "02/02/2024",
    href: "/routes/the-wurliest-burliest-man",
    location: "main1",
  },
  {
    name: "The Long Dive",
    grade: "5.8",
    color: "yellow",
    type: "toprope",
    id: "00002",
    image: "/img/rope2.jpg",
    description: "A long climb with a lot of exposure",
    date: "02/03/2024",
    href: "/routes/the-long-dive",
    location: "main2",
  },
  {
    name: "The Crux Crusher",
    grade: "5.12",
    color: "red",
    type: "lead",
    id: "00003",
    image: "/img/rope2.jpg",
    description: "A challenging climb with a difficult crux",
    date: "02/04/2024",
    href: "/routes/the-crux-crusher",
    location: "main2",
  },
  {
    name: "The Slab Master",
    grade: "5.6",
    color: "gray",
    type: "toprope",
    id: "00004",
    image: "/img/rope2.jpg",
    description: "A technical climb on a slab wall",
    date: "02/05/2024",
    href: "/routes/the-slab-master",
    location: "AB",
  },
  {
    name: "Cheese has protein?",
    grade: "5.8",
    color: "orange",
    type: "boulder",
    id: "00005",
    image: "/img/boulder1.jpg",
    description: "A powerful dyno move required to complete the climb",
    date: "02/06/2024",
    href: "/routes/cheese-has-protein",
    location: "main1",
  },
];

export const boulderRoutes = [
  {
    name: "The Boulder Problem",
    grade: "V2",
    color: "green",
    id: "00001",
    image: "/img/boulder1.jpg",
    discription: "A long climb with a lot of exposure",
    date: "2021-06-02",
    href: "/routes/the-boulder-problem",
    location: "boulder2",
  },
  {
    name: "The Dyno King",
    grade: "V5",
    color: "orange",
    type: "boulder",
    id: "00005",
    image: "/img/boulder1.jpg",
    description: "A powerful dyno move required to complete the climb",
    date: "02/06/2024",
    href: "/routes/the-dyno-king",
    location: "boulder1",
  },
  {
    name: "wow nice moves",
    grade: "V5",
    color: "green",
    type: "boulder",
    id: "00005",
    image: "/img/boulder1.jpg",
    description: "A powerful dyno move required to complete the climb",
    date: "02/06/2024",
    href: "/routes/the-dyno-king",
    location: "boulder1",
  },
];
export const events = [
  {
    name: "2024 Ropes League",
    date: "2024-06-02",
    image: "/img/trophy.png",
    id: "00001",
    active: true,
    href: "/events/2024-ropes-league",
  },
];
export const profiles = [
  {
    username: "ehonis",
    name: "Ethan",
    email: "e-24@live.com",
    admin: false,
    image: "../Images/default.jpg",
    password: "password1234",
  },
  {
    name: "OTR_DJ",
    name: "DJ",
    email: "dj@gmail.com",
    admin: true,
    image: "../Images/default.jpg",
    password: "password1234",
  },
];
export let currentUser = {
  name: "OTR_DJ",
  name: "DJ",
  email: "dj@gmail.com",
  admin: false,
  image: "../Images/default.jpg",
  password: "password1234",
};
