import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./ui/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-bg0`}>
        <div className="outline-red-500 fixed left-0 top-0 rounded-br-lg bg-bg1 p-1 text-white outline">
          Demo
        </div>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
