import { Inter } from "next/font/google";
import "./globals.css";
import MobileNav from "./ui/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="fixed inset-x-0 bottom-0 left-0 h-16 overflow-hidden bg-bg1">
          <MobileNav />
        </div>
        {children}
      </body>
    </html>
  );
}
